In [3]:
import yfinance as yf

In [32]:
tsla = yf.Ticker('TSLA')

In [35]:
tsla = tsla.history(period = 'max') # 1mo, 1y, min

In [36]:
tsla

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...
2023-12-27 00:00:00-05:00,258.350006,263.339996,257.519989,261.440002,106494400,0.0,0.0
2023-12-28 00:00:00-05:00,263.660004,265.130005,252.710007,253.179993,113619900,0.0,0.0
2023-12-29 00:00:00-05:00,255.100006,255.190002,247.429993,248.479996,100615300,0.0,0.0
2024-01-02 00:00:00-05:00,250.080002,251.250000,244.410004,248.419998,104654200,0.0,0.0
2024-01-03 00:00:00-05:00,244.979996,245.679993,236.320007,238.449997,120779500,0.0,0.0

In [34]:
# show share count
tsla = yf.Ticker('TSLA')
tsla.get_shares_full(start = '2021-01-01', end = None)

2021-02-09 00:00:00-05:00     959854016
2021-03-17 00:00:00-04:00     983747968
2021-03-17 00:00:00-04:00     959854016
2021-04-14 00:00:00-04:00     883878016
2021-04-14 00:00:00-04:00     959854016
                                ...
2023-12-23 00:00:00-05:00    3203589888
2023-12-26 00:00:00-05:00    3178919936
2023-12-27 00:00:00-05:00    3178919936
2023-12-28 00:00:00-05:00    3178919936
2023-12-30 00:00:00-05:00    3178919936
Length: 112, dtype: int64

In [39]:
# show income statement
tsla = yf.Ticker('TSLA')
tsla.income_stmt

,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,-14080000.0,2970000.0,0.0
Tax Rate For Calcs,0.08,0.11,0.25
Normalized EBITDA,17833000000.0,9598000000.0,4224000000.0
Total Unusual Items,-176000000.0,27000000.0,0.0
Total Unusual Items Excluding Goodwill,-176000000.0,27000000.0,0.0
Net Income From Continuing Operation Net Minority Interest,12583000000.0,5519000000.0,690000000.0
Reconciled Depreciation,3747000000.0,2911000000.0,2322000000.0
Reconciled Cost Of Revenue,60609000000.0,40217000000.0,24906000000.0
EBITDA,17657000000.0,9625000000.0,4224000000.0
EBIT,13910000000.0,6714000000.0,1902000000.0
Net Interest Income,106000000.0,-315000000.0,-718000000.0
Interest Expense,191000000.0,371000000.0,748000000.0
Interest Income,297000000.0,56000000.0,30000000.0
Normalized Income,12744920000.0,5494970000.0,690000000.0
Net Income From Continuing And Discontinued Operation,12583000000.0,5519000000.0,690000000.0
Total Expenses,67630000000.0,47327000000.0,29542000000.0
Total Operating Income As Reported,13656000000.0,-6523000000.0,1994000000.0
Diluted Average Shares,3475000000.0,3387000000.0,3249000000.0
Basic Average Shares,3130000000.0,2958000000.0,2799000000.0
Diluted EPS,3.62,1.633333,0.213333
Basic EPS,4.02,1.866667,0.246667
Diluted NI Availto Com Stockholders,12584000000.0,5519000000.0,690000000.0
Average Dilution Earnings,1000000.0,NaN,NaN
Net Income Common Stockholders,12583000000.0,5519000000.0,690000000.0
Net Income,12583000000.0,5519000000.0,690000000.0
Minority Interests,-4000000.0,-125000000.0,-172000000.0
Net Income Including Noncontrolling Interests,12587000000.0,5644000000.0,862000000.0
Net Income Continuous Operations,12587000000.0,5644000000.0,862000000.0
Tax Provision,1132000000.0,699000000.0,292000000.0
Pretax Income,13719000000.0,6343000000.0,1154000000.0
Other Income Expense,-219000000.0,162000000.0,-122000000.0
Other Non Operating Income Expenses,-43000000.0,135000000.0,-122000000.0
Special Income Charges,-176000000.0,27000000.0,0.0
Restructuring And Mergern Acquisition,176000000.0,-27000000.0,0.0
Net Non Operating Interest Income Expense,106000000.0,-315000000.0,-718000000.0
Interest Expense Non Operating,191000000.0,371000000.0,748000000.0
Interest Income Non Operating,297000000.0,56000000.0,30000000.0
Operating Income,13832000000.0,6496000000.0,1994000000.0
Operating Expense,7021000000.0,7110000000.0,4636000000.0
Research And Development,3075000000.0,2593000000.0,1491000000.0
Selling General And Administration,3946000000.0,4517000000.0,3145000000.0
Gross Profit,20853000000.0,13606000000.0,6630000000.0
Cost Of Revenue,60609000000.0,40217000000.0,24906000000.0
Total Revenue,81462000000.0,53823000000.0,31536000000.0
Operating Revenue,81462000000.0,53823000000.0,31536000000.0

In [40]:
tsla.quarterly_income_stmt

,2023-09-30,2023-06-30,2023-03-31,2022-12-31
Tax Effect Of Unusual Items,0.0,0.0,0.0,-2356013.055486
Tax Rate For Calcs,0.081663,0.109976,0.093214,0.069295
Normalized EBITDA,3318000000.0,4119000000.0,3875000000.0,5039000000.0
Total Unusual Items,0.0,0.0,0.0,-34000000.0
Total Unusual Items Excluding Goodwill,0.0,0.0,0.0,-34000000.0
Net Income From Continuing Operation Net Minority Interest,1853000000.0,2703000000.0,2513000000.0,3687000000.0
Reconciled Depreciation,1235000000.0,1154000000.0,1046000000.0,989000000.0
Reconciled Cost Of Revenue,19172000000.0,20394000000.0,18818000000.0,18541000000.0
EBITDA,3318000000.0,4119000000.0,3875000000.0,5005000000.0
EBIT,2083000000.0,2965000000.0,2829000000.0,4016000000.0
Net Interest Income,244000000.0,210000000.0,184000000.0,124000000.0
Interest Expense,38000000.0,28000000.0,29000000.0,33000000.0
Interest Income,282000000.0,238000000.0,213000000.0,157000000.0
Normalized Income,1853000000.0,2703000000.0,2513000000.0,3718643986.944514
Net Income From Continuing And Discontinued Operation,1853000000.0,2703000000.0,2513000000.0,3687000000.0
Total Expenses,21586000000.0,22528000000.0,20665000000.0,20383000000.0
Total Operating Income As Reported,1764000000.0,2399000000.0,2664000000.0,3901000000.0
Diluted Average Shares,3493000000.0,3478000000.0,3468000000.0,3471000000.0
Basic Average Shares,3176000000.0,3171000000.0,3166000000.0,3160000000.0
Diluted EPS,0.53,0.78,0.73,1.07
Basic EPS,0.58,0.85,0.8,1.18
Diluted NI Availto Com Stockholders,1853000000.0,2703000000.0,2513000000.0,3687000000.0
Average Dilution Earnings,0.0,0.0,NaN,0.0
Net Income Common Stockholders,1853000000.0,2703000000.0,2513000000.0,3687000000.0
Otherunder Preferred Stock Dividend,2000000.0,0.0,NaN,NaN
Net Income,1853000000.0,2703000000.0,2513000000.0,3687000000.0
Minority Interests,-25000000.0,89000000.0,-26000000.0,-20000000.0
Net Income Including Noncontrolling Interests,1878000000.0,2614000000.0,2539000000.0,3707000000.0
Net Income Continuous Operations,1878000000.0,2614000000.0,2539000000.0,3707000000.0
Tax Provision,167000000.0,323000000.0,261000000.0,276000000.0
Pretax Income,2045000000.0,2937000000.0,2800000000.0,3983000000.0
Other Income Expense,37000000.0,328000000.0,-48000000.0,-76000000.0
Other Non Operating Income Expenses,37000000.0,328000000.0,-48000000.0,-42000000.0
Special Income Charges,0.0,0.0,0.0,-34000000.0
Restructuring And Mergern Acquisition,0.0,0.0,0.0,34000000.0
Net Non Operating Interest Income Expense,244000000.0,210000000.0,184000000.0,124000000.0
Interest Expense Non Operating,38000000.0,28000000.0,29000000.0,33000000.0
Interest Income Non Operating,282000000.0,238000000.0,213000000.0,157000000.0
Operating Income,1764000000.0,2399000000.0,2664000000.0,3935000000.0
Operating Expense,2414000000.0,2134000000.0,1847000000.0,1842000000.0
Research And Development,1161000000.0,943000000.0,771000000.0,810000000.0
Selling General And Administration,1253000000.0,1191000000.0,1076000000.0,1032000000.0
Gross Profit,4178000000.0,4533000000.0,4511000000.0,5777000000.0
Cost Of Revenue,19172000000.0,20394000000.0,18818000000.0,18541000000.0
Total Revenue,23350000000.0,24927000000.0,23329000000.0,24318000000.0
Operating Revenue,23350000000.0,24927000000.0,23329000000.0,24318000000.0

In [41]:
# balance sheet
tsla.balance_sheet

,2022-12-31,2021-12-31,2020-12-31
Ordinary Shares Number,3164000000.0,3099000000.0,2880000000.0
Share Issued,3164000000.0,3099000000.0,2880000000.0
Total Debt,3099000000.0,6834000000.0,11739000000.0
Tangible Book Value,44111000000.0,28472000000.0,21705000000.0
Invested Capital,47803000000.0,37023000000.0,33964000000.0
...,...,...,...
Receivables,2952000000.0,1913000000.0,1886000000.0
Accounts Receivable,2952000000.0,1913000000.0,1886000000.0
Cash Cash Equivalents And Short Term Investments,22185000000.0,17707000000.0,19384000000.0
Other Short Term Investments,5932000000.0,131000000.0,NaN
Cash And Cash Equivalents,22185000000.0,17576000000.0,19384000000.0

In [42]:
# cash flow statement
tsla.cashflow

,2022-12-31,2021-12-31,2020-12-31
Free Cash Flow,7552000000.0,3483000000.0,2701000000.0
Repayment Of Debt,-3866000000.0,-14615000000.0,-12201000000.0
Issuance Of Debt,0.0,8883000000.0,9713000000.0
Issuance Of Capital Stock,0.0,0.0,12269000000.0
Capital Expenditure,-7172000000.0,-8014000000.0,-3242000000.0
Interest Paid Supplemental Data,152000000.0,266000000.0,444000000.0
Income Tax Paid Supplemental Data,1203000000.0,561000000.0,115000000.0
End Cash Position,16924000000.0,18144000000.0,19901000000.0
Beginning Cash Position,18144000000.0,19901000000.0,6783000000.0
Effect Of Exchange Rate Changes,-444000000.0,-183000000.0,334000000.0
Changes In Cash,-776000000.0,-1574000000.0,12784000000.0
Financing Cash Flow,-3527000000.0,-5203000000.0,9973000000.0
Cash Flow From Continuing Financing Activities,-3527000000.0,-5203000000.0,9973000000.0
Net Other Financing Charges,-202000000.0,-178000000.0,-225000000.0
Proceeds From Stock Option Exercised,541000000.0,707000000.0,417000000.0
Net Common Stock Issuance,0.0,0.0,12269000000.0
Common Stock Issuance,0.0,0.0,12269000000.0
Net Issuance Payments Of Debt,-3866000000.0,-5732000000.0,-2488000000.0
Net Long Term Debt Issuance,-3866000000.0,-5732000000.0,-2488000000.0
Long Term Debt Payments,-3866000000.0,-14615000000.0,-12201000000.0
Long Term Debt Issuance,0.0,8883000000.0,9713000000.0
Investing Cash Flow,-11973000000.0,-7868000000.0,-3132000000.0
Cash Flow From Continuing Investing Activities,-11973000000.0,-7868000000.0,-3132000000.0
Net Other Investing Changes,76000000.0,6000000.0,123000000.0
Net Investment Purchase And Sale,-5813000000.0,-132000000.0,NaN
Sale Of Investment,22000000.0,NaN,NaN
Purchase Of Investment,-5835000000.0,-132000000.0,NaN
Net Business Purchase And Sale,0.0,0.0,-13000000.0
Sale Of Business,0.0,NaN,NaN
Purchase Of Business,0.0,0.0,-13000000.0
Net Intangibles Purchase And Sale,927000000.0,-1228000000.0,-10000000.0
Sale Of Intangibles,936000000.0,272000000.0,NaN
Purchase Of Intangibles,-9000000.0,-1500000000.0,-10000000.0
Net PPE Purchase And Sale,-7163000000.0,-6514000000.0,-3232000000.0
Purchase Of PPE,-7163000000.0,-6514000000.0,-3232000000.0
Operating Cash Flow,14724000000.0,11497000000.0,5943000000.0
Cash Flow From Continuing Operating Activities,14724000000.0,11497000000.0,5943000000.0
Change In Working Capital,-3908000000.0,518000000.0,184000000.0
Change In Other Working Capital,1286000000.0,979000000.0,328000000.0
Change In Other Current Liabilities,1904000000.0,476000000.0,495000000.0
Change In Other Current Assets,-4121000000.0,-3405000000.0,-1416000000.0
Change In Payables And Accrued Expense,6029000000.0,4578000000.0,2102000000.0
Change In Prepaid Assets,-1417000000.0,-271000000.0,-251000000.0
Change In Inventory,-6465000000.0,-1709000000.0,-422000000.0
Change In Receivables,-1124000000.0,-130000000.0,-652000000.0
Changes In Account Receivables,-1124000000.0,-130000000.0,-652000000.0
Other Non Cash Items,340000000.0,245000000.0,408000000.0
Stock Based Compensation,1560000000.0,2121000000.0,1734000000.0
Asset Impairment Charge,177000000.0,140000000.0,202000000.0
Depreciation Amortization Depletion,3747000000.0,2911000000.0,2322000000.0
Depreciation And Amortization,3747000000.0,2911000000.0,2322000000.0
Depreciation,3747000000.0,2911000000.0,NaN
Operating Gains Losses,221000000.0,-82000000.0,231000000.0
Net Foreign Currency Exchange Gain Loss,81000000.0,-55000000.0,114000000.0
Gain Loss On Sale Of PPE,140000000.0,-27000000.0,117000000.0
Net Income From Continuing Operations,12587000000.0,5644000000.0,862000000.0

In [43]:
# show holders
tsla.major_holders

        0                                      1
0  13.02%        % of Shares Held by All Insider
1  44.70%       % of Shares Held by Institutions
2  51.39%        % of Float Held by Institutions
3    3674  Number of Institutions Holding Shares

In [44]:
tsla.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Group Inc,225940011,2023-09-29,0.0711,53875394933
1,Blackrock Inc.,186653186,2023-09-29,0.0587,44507451632
2,State Street Corporation,104861369,2023-09-29,0.0330,25004193118
3,"Geode Capital Management, LLC",53875703,2023-09-29,0.0169,12846661215
4,Capital World Investors,41103054,2023-09-29,0.0129,9801023100
5,Morgan Stanley,30160747,2023-09-29,0.0095,7191830030
6,JP Morgan Chase & Company,29419060,2023-09-29,0.0093,7014974767
7,"FMR, LLC",29040734,2023-09-29,0.0091,6924762933
8,Norges Bank Investment Management,28085245,2022-12-30,0.0088,6696926584
9,Northern Trust Corporation,27542824,2023-09-29,0.0087,6567586298

In [45]:
tsla.mutualfund_holders

,Holder,Shares,Date Reported,% Out,Value
0,Vanguard Total Stock Market Index Fund,84006460,2023-09-29,0.0264,20031340130
1,Vanguard 500 Index Fund,66358271,2023-09-29,0.0209,15823129517
2,Fidelity 500 Index Fund,31973001,2023-10-30,0.0101,7623961990
3,SPDR S&P 500 ETF Trust,30812229,2023-09-29,0.0097,7347175911
4,iShares Core S&P 500 ETF,26057361,2023-09-29,0.0082,6213377650
5,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",25303098,2023-09-29,0.0080,6033523640
6,Vanguard Growth Index Fund,23413536,2023-09-29,0.0074,5582957587
7,Growth Fund Of America Inc,22548737,2023-09-29,0.0071,5376746268
8,Vanguard Institutional Index Fund-Institutiona...,18528798,2023-09-29,0.0058,4418191826
9,Select Sector SPDR Fund-Consumer Discretionary,14018471,2023-09-29,0.0044,3342704367

In [47]:
# options expirations
tsla.options

('2024-01-05',
 '2024-01-12',
 '2024-01-19',
 '2024-01-26',
 '2024-02-02',
 '2024-02-09',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-07-19',
 '2024-09-20',
 '2025-01-17',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16')

In [54]:
# show news
for i in tsla.news:
    print(i['title'])

Dow Jones Futures: Market Losses Broaden; Cathie Wood Buys Tesla, Sells This Bitcoin Stock
GM, Stellantis US Sales Hit by UAW Strikes, High Sticker Prices
Apple Leads $383Â Billion Tech Rout in Reversal From Groupâ€™s 2023 Rally
Tesla Reported Record Deliveries. Here's Why Wall Street Is Keeping Its Powder Dry.
Magnificent Seven Stocks To Buy And Watch: Apple, Nvidia, Tesla Slide
Tesla, Auto Stocks Drop
'This is not a game': Secy. Buttigieg talks looming shutdown
North America Is Advancing With Its EV Power-Shift Efforts